<a href="https://colab.research.google.com/github/andrerizzo/complete_project/blob/code/Modelagem_with_Bayesian_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [96]:
# Import libraries
import numpy as np
import pandas as pd

In [97]:
# Import dataset
#url = 'https://raw.githubusercontent.com/andrerizzo/complete_project/dataset/iris.csv'
#df = pd.read_csv(url)

file = "c:/Temp/Iris/data/processed/iris.csv"
df = pd.read_csv(file)

print(df)

     sepal_length  sepal_width  petal_length_trans  petal_width_trans  class
0             4.9          3.0           -1.222611          -1.122276      0
1             4.7          3.2           -1.641609          -1.122276      0
2             4.6          3.1           -0.860957          -1.122276      0
3             5.0          3.6           -1.222611          -1.122276      0
4             5.4          3.9           -0.518618          -0.547708      0
..            ...          ...                 ...                ...    ...
144           6.7          3.0            0.767216           1.497635      2
145           6.3          2.5            0.537961           0.801541      2
146           6.5          3.0            0.767216           0.936544      2
147           6.2          3.4            0.860957           1.497635      2
148           5.9          3.0            0.658733           0.617488      2

[149 rows x 5 columns]


In [98]:
# Handling Categorical Variables

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform(y.values.ravel())

print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]


In [99]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X = df.iloc[:,[3]]
y = df.iloc[:,4]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

     petal_width_trans
27           -1.122276
97           -0.290005
96           -0.067343
69            0.617488
18           -0.690416
..                 ...
9            -1.122276
103           1.258935
67            0.281244
117           1.497635
47           -1.122276

[119 rows x 1 columns]
     petal_width_trans
133           0.109568
109           0.936544
59           -0.378986
80           -0.378986
7            -1.122276
104           1.106624
140           1.497635
95           -0.067343
118           0.281244
84            0.424583
33           -2.050984
44           -0.690416
54           -0.067343
24           -1.122276
37           -1.122276
132           0.281244
111           1.106624
73           -0.067343
16           -0.690416
45           -1.122276
40           -0.690416
8            -2.050984
85            0.281244
22           -0.471080
62            0.109568
94           -0.220472
90            0.109568
26           -1.122276
43           -0.547708
134       

In [100]:
# Create dictionary to store accuracy results
results = {}

In [101]:
# Evaluate Models - LDA

# Import libraries
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = LDA()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("Linear Discriminant Analysis model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['LDA'] = np.mean(scores)

Linear Discriminant Analysis model accuracy: 0.950 (0.070) 



In [102]:
# Evaluate Models - kNN

# Import libraries
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = KNeighborsClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores= 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("k-Nearest Neighbors model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['kNN'] = np.mean(scores)

k-Nearest Neighbors model accuracy: 0.967 (0.051) 



In [103]:
# Evaluate Models - SVC

# Import libraries
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = SVC(kernel='linear')

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("Support Vector Classifier model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['SVC'] = np.mean(scores)

Support Vector Classifier model accuracy: 0.922 (0.086) 



In [104]:
# Evaluate Models - SGD

# Import libraries
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = SGDClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("Stochastic Gradient Descend model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['SGD'] = np.mean(scores)

Stochastic Gradient Descend model accuracy: 0.891 (0.092) 



In [105]:
# Evaluate Models - Gaussian Naive Bayes

# Import libraries
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = GaussianNB()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("Naive Bayes model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['Gaussian Naive Bayes'] = np.mean(scores)

Naive Bayes model accuracy: 0.967 (0.051) 



In [106]:
# Evaluate Models - Decision Tree

# Import libraries
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = DecisionTreeClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("Decision Tree Classifier model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['Decision Trees'] = np.mean(scores)

Decision Tree Classifier model accuracy: 0.958 (0.056) 



In [107]:
# Evaluate Models - Random Forest

# Import libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = RandomForestClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1, error_score='raise')

print("Random Forerst model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['Random Forest'] = np.mean(scores)

Random Forerst model accuracy: 0.953 (0.056) 



In [108]:
# Evaluate Models - AdaBoost

# Import libraries
from sklearn.ensemble import AdaBoostClassifier

# Define model
classifier = AdaBoostClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1, error_score='raise')

print("AdaBoost model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['AdaBoost'] = np.mean(scores)

AdaBoost model accuracy: 0.958 (0.056) 



In [109]:
# Evaluate Models - MLP Classifier

# Import libraries
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = MLPClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("Multi-Layer Perceptron Model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['MLP Classifier'] = np.mean(scores)

Multi-Layer Perceptron Model accuracy: 0.967 (0.051) 



In [110]:
# Show results
import csv

results = sorted(results.items(), reverse=True, key=lambda item: item[1])

with open('Results.csv', 'w') as f:
    write = csv.writer(f)
    write.writerows(results)

results    

[('kNN', 0.9666666666666668),
 ('Gaussian Naive Bayes', 0.9666666666666668),
 ('MLP Classifier', 0.9666666666666668),
 ('Decision Trees', 0.9583333333333335),
 ('AdaBoost', 0.9583333333333335),
 ('Random Forest', 0.9527777777777778),
 ('LDA', 0.95),
 ('SVC', 0.9217171717171717),
 ('SGD', 0.8911616161616163)]

In [66]:
# Hyperparameter tuning - SVC
from skopt import BayesSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.svm import SVC

# define search space
hparams = dict()
hparams['C'] = (1e-6, 100.0, 'log-uniform')
hparams['gamma'] = (1e-6, 100.0, 'log-uniform')
hparams['degree'] = (1,5)
hparams['kernel'] = ['linear', 'poly', 'rbf', 'sigmoid']

# Define evaluation
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Define Optimization Parameters
search = BayesSearchCV(estimator=SVC(), search_spaces=hparams, n_jobs=-1, cv=cv)

# Perform the search
search.fit(X_train, y_train)

# Store result
SVC_hyper_result = search.best_params_

# Report best result
print("Best hyperparameters:")
print(SVC_hyper_result, "\n")
print("SVC model accuracy after best hyperparameter definition: %.3f" % (search.best_score_))

KeyboardInterrupt: 

In [111]:
# Hyperparameter tuning - kNN
from skopt import BayesSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.neighbors import KNeighborsClassifier as clf

# define search space
hparams = dict()
hparams['n_neighbors'] = (1, 20, 'uniform')
hparams['weights'] = ('uniform', 'distance')
hparams['p'] = (1, 2)

# Define evaluation
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=0)

# Define the search
search = BayesSearchCV(estimator=clf(), search_spaces=hparams, n_jobs=-1, cv=cv)

# Perform the search
search.fit(X_train, y_train)

# Store result
kNN_hyper_result = search.best_params_

# Report best result
print("Best hyperparameters:")
print(kNN_hyper_result, "\n")
print("kNN model accuracy after best hyperparameter definition: %.3f" % (search.best_score_))

C:\Users\andre.rizzo\Anaconda3\lib\site-packages\skopt\optimizer\optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
C:\Users\andre.rizzo\Anaconda3\lib\site-packages\skopt\optimizer\optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
C:\Users\andre.rizzo\Anaconda3\lib\site-packages\skopt\optimizer\optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
C:\Users\andre.rizzo\Anaconda3\lib\site-packages\skopt\optimizer\optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
C:\Users\andre.rizzo\Anaconda3\lib\site-packages\skopt\optimizer\optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has be

Best hyperparameters:
OrderedDict([('n_neighbors', 10), ('p', 1), ('weights', 'uniform')]) 

kNN model accuracy after best hyperparameter definition: 0.972


In [22]:
# Hyperparameter tuning - Random Forest (using tune_sklearn)

from tune_sklearn import TuneSearchCV
from sklearn.ensemble import RandomForestClassifier as clf

# define search space
hparams = dict()
hparams['n_estimators'] = (1, 1000, 'uniform')
hparams['criterion'] = ['gini', 'entropy']
hparams['max_leaf_nodes'] = (2,100, "uniform")

# Define evaluation
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Define the search
search = BayesSearchCV(estimator=clf(), search_spaces=hparams, n_jobs=-1, cv=cv)

# Perform the search
search.fit(X_train, y_train)

# Store result
RF_hyper_result = search.best_params_

# Report best result
print("Best hyperparameters:")
print(RF_hyper_result, "\n")
print("Random Forest model accuracy after best hyperparameter definition: %.3f" % (search.best_score_))

Best hyperparameters:
OrderedDict([('criterion', 'gini'), ('max_leaf_nodes', 64), ('n_estimators', 407)]) 

Random Forest model accuracy after best hyperparameter definition: 0.927


In [112]:
# Hyperparameter tuning - LDA (using tune_sklearn)

from tune_sklearn import TuneSearchCV
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA


# define search space
hparams = dict()
hparams['solver'] = ['lsqr', 'eigen']
hparams['shrinkage'] = (None,'auto')
#hparams['n_components'] = (1, 2)
hparams['tol'] = (1e-6, 1e10, "log-uniform")


# Define evaluation
#cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Define the search
search = TuneSearchCV(LDA(),
                           param_distributions = hparams,
                           use_gpu = False,
                           cv = 10,
                           n_jobs = 1,
                           search_optimization = 'bayesian',
                           refit = True,
                           verbose=0, 
                           random_state=1
                          )
                      
# Perform the search
search.fit(X_train, y_train)

# Store result
LDA_hyper_result = search.best_params_

# Report best result
print("Best hyperparameters:")
print(LDA_hyper_result, "\n")
print("LDA model accuracy after best hyperparameter definition: %.3f" % (search.best_score_))

fail_fast='raise' detected. Be careful when using this mode as resources (such as Ray processes, file descriptors, and temporary files) may not be cleaned up properly. To use a safer mode, use fail_fast=True.
Log sync requires rsync to be installed.
Trial Runner checkpointing failed: cannot pickle 'dict_values' object
Trial _Trainable_e970846a: Error processing event.
Traceback (most recent call last):
  File "C:\Users\andre.rizzo\Anaconda3\lib\site-packages\ray\tune\trial_runner.py", line 534, in _process_trial
    self._search_alg.on_trial_complete(
  File "C:\Users\andre.rizzo\Anaconda3\lib\site-packages\ray\tune\suggest\search_generator.py", line 143, in on_trial_complete
    self.searcher.on_trial_complete(
  File "C:\Users\andre.rizzo\Anaconda3\lib\site-packages\ray\tune\suggest\suggestion.py", line 352, in on_trial_complete
    self.searcher.on_trial_complete(
  File "C:\Users\andre.rizzo\Anaconda3\lib\site-packages\ray\tune\suggest\skopt.py", line 247, in on_trial_complete
    

ValueError: array must not contain infs or NaNs

In [15]:
# Train SVC model using computed hyperparameters

from sklearn.svm import SVC
import sklearn.metrics as clf_metrics


# Defining model with hyperparameters
model = SVC(C = SVC_hyper_result["C"], 
            kernel = SVC_hyper_result["kernel"],
            degree = SVC_hyper_result["degree"],
            gamma = SVC_hyper_result["gamma"],
           )

# Fitting model to train set
model.fit(X_train, y_train)

# Predicting with testing set
y_pred = model.predict(X_test)

#clf_metrics.auc(y_test, y_pred)

# Show metrics
print('Confusion matrix')
print(clf_metrics.confusion_matrix(y_test, y_pred),"\n")
print('Accuracy score:', clf_metrics.accuracy_score(y_test, y_pred),"\n")
print('Class weights')
print(model.class_weight_)


Confusion matrix
[[12  0  0]
 [ 0 10  0]
 [ 0  0  8]] 

Accuracy score: 1.0 

Class weights
[1. 1. 1.]


In [ ]:
# Train kNN model using computed hyperparameters

